### ISSUE TITLE
Optional token normalization in NLP server

### ISSUE THREAD

**Issue by nopper** [factorie/factorie#283]
Hi there, I am using factorie NLP server but found it implicitly does some token normalization. For example in this case:

```
$ nc localhost 3228
Half of investors expect Greece to leave euro zone

1       1       Half            NN      4       nsubj   O
2       2       of              IN      1       prep    O
3       3       investors               NNS     2       pobj    O
4       4       expect          VBP     0       root    O
5       5       Greece          NNP     7       nsubj   U-LOC
6       6       to              TO      7       aux     O
7       7       leave           VB      4       ccomp   O
8       8       $               $       10      nn      O <--------
9       9       o               JJ      10      amod    O <--------
10      10      zone            NN      7       dobj    O
```

The token `Euro` token gets split into two distinct tokens, `$` and `o` respectively. Since I am interested in obtaining the start offset of each token with respect to the original text (e.g. the token `zone` is at offset 46), I was wondering if is it possible to disable token normalization or to obtain this information somehow.

**Comment by strubell** [comment]
Hi Francesco, right now there is not an option to disable normalization but
I will add one momentarily :)

**Comment by strubell** [comment]
Should be resolved by PR #284, --token should no longer normalize, and there is a new option --token-norm that will normalize.

**Comment by nopper** [comment]
Sorry to reopen this issue again. I started a new NLP server with the `--token` option but found another example in which normalization occurs:

```
$ nc localhost 3228
Hello - there

1       1       Hello           0       5       NNP     0       root    O
2       2       --              6       7       :       1       punct   O <---- should be a single dash not double
3       3       there           8       13      RB      1       advmod  O
```

**Comment by strubell** [comment]
Are you sure you're using the latest version, including my fix? Tokenizing
the same text with the tokenizer directly, I get "Hello - there" -- I
haven't tried with the server yet, but I will soon.

I just realized that your previous example points out a bug, we shouldn't
be tokenizing euro as
"eur o" or "$ o" at all, so thanks for pointing that out!

**Comment by strubell** [comment]
I just verified I get the same results (no normalization) via the NLP
server. Can you give me the exact command you're using to start the server?

**Comment by nopper** [comment]
I am using the following:

``bin/fac nlp --token --wsj-forward-pos --transition-based-parser --stacked-chain-ner-noembeddings``

I've also tried to edit the `DeterministicLexerTokenizer` class with in order to force all the normalization to `false` but got the same results:

```
object DeterministicTokenizer extends DeterministicLexerTokenizer(
  tokenizeSgml = false,
  tokenizeNewline = false,
  tokenizeWhitespace = false,
  tokenizeAllDashedWords = false,
  abbrevPrecedesLowercase = false,
  normalize = false,
  normalizeQuote = false,
  normalizeApostrophe = false,
  normalizeCurrency = false,
  normalizeAmpersand = false,
  normalizeFractions = false,
  normalizeEllipsis = false,
  undoPennParens = false,
  unescapeSlash = false,
  unescapeAsterisk = false,
  normalizeMDash = false,
  normalizeDash = false,
  normalizeHtmlSymbol = false,
  normalizeHtmlAccent = false
)
```

**Comment by strubell** [comment]
Ah, I see, the pos tagger normalizes tokens, which is why you're getting
normalized token strings in your output. The fourth field gives character
offsets in the original string, though, which I think is what you need?
