### ISSUE TITLE
No jflex configuration in Sbt buildscript

### ISSUE THREAD

**Issue by GoGoris** [factorie/factorie#290]
In the Build.scala file, a compiler for EnglishLexer.flex is missing. I found a sbt-jflex plugin but I can't find how to configure it to compile src/main/scala/cc/factorie/app/nlp/segment.

**Comment by strubell** [comment]
Oops! This is an oversight on my part. I'll look in to it as soon as I get
a chance (unfortunately this may require modifying the sbt-jflex plugin to
use our non-standard jflex-scala). Thanks for pointing this out!

**Comment by strubell** [comment]
Should be resolved by PR #292, thanks!

**Comment by GoGoris** [comment]
Thank you for the quick fix!
