### ISSUE TITLE
Inconsistent behavior in CategoricalDomain

### ISSUE THREAD

**Issue by k8si** [factorie/factorie#305]
In CategoricalDomain, the method "+=" looks like:

`def +=(x:C) : Unit = this.value(x)`

and the method "++=" looks like:

`def ++=(xs:Traversable[C]) : Unit = xs.foreach(this.index(_))`

This means that, if `gatherCounts = true` and the user adds something to a CategoricalDomain using `+=`, the domain WON'T update the count (because `value(x: C)` never seems to update counts), but using `++=`, the domain WILL update counts (since `index(x: C)` first updates counts, then calls `value`) 

Here is a gist demonstrating this issue:  https://gist.github.com/k8si/8595b4460a3e11802dba

I propose that we make the changes:

`def +=(x: C): Unit = this.index(x)`
`def ++=(xs: Traversable[C]): Unit = xs.foreach(this += _)`

I am submitting this as an issue rather than a pull request because I believe it merits some discussion re: what the behaviour should be here.

**Comment by andrewmccallum** [comment]
I agree with your suggested change.
