### ISSUE TITLE
After NER tagging Documents have a reference to the NER model itself

### ISSUE THREAD

**Issue by Craigacp** [factorie/factorie#330]
When tagging Documents using the StackedChainNer model, each Document has a ChainNerFeatures and ChainNer2Features added to each Token's attr. These features have references to two large objects (the ChainNer{2}FeatureDomain and the StackedChainNer model itself) which causes problems when serializing a list of Documents (e.g. when transferring tagged Documents over the network in Spark, or serializing them directly to disk), as it also serialises up to 600MB of NER model. It's particularly bad if you send a single Document across the network as each Document will pull in the whole model.

The ChainNerFeatures have a reference to the StackedChainNer model because they are inner classes (and unlike Java that means they have a reference to the outer class). I propose moving them (and the associated Domains) outside the class, making the domains a class instead of an object, adding a val field to StackedChainNer to store the instance of the domain. I'll work up a pull request along these lines if you think that sounds sensible.

@k8si ran into this issue during her internship and had code to remove the Features from each Document after NER tagging had completed (in the process method I think). It will be easier to do this once the Features are moved outside the class because the Features class will be a concrete type that can be referenced from anywhere (as otherwise you need a reference to the NER model to supply the correct Class to the attr.remove method, which is hard when using NER in a DocumentAnnotationPipeline). This will allow the features to be removed after the pipeline has processed them directly before serialisation (as the features may be useful to a later DocumentAnnotator).

**Comment by strubell** [comment]
Why not just modify the tagger to remove the attrs containing features after they are used for prediction?

**Comment by Craigacp** [comment]
Sure, assuming the features aren't used anywhere else. Is there a firm decision on whether the features should be added to an attr or not in general? They are added (and left on the Document) in some cases, and not added in others.

**Comment by strubell** [comment]
afaik whether or not to add features to the document is entirely up to the individual implementing the tagger, and I don't know of any case in which they are used later. Personally I don't think that leaving them on should be the default behavior
