### ISSUE TITLE
Deprecating octal literals

### ISSUE THREAD

**Issue by Craigacp** [factorie/factorie#353]
Just a heads up, I compiled factorie with deprecation warnings turned on and maven generated 3.7GBs of output complaining about the octal literals generated by JFlex for the DeterministicLexerTokenizer. There were 350973 warnings in total, most of which are from the lexer as it has one warning for each octal literal, and it's basically all octal literals.

**Comment by strubell** [comment]
I spent a significant amount of time trying to avoid this when I wrote the Scala version of JFlex. Unfortunately the only way to generate a lexer that doesn't overflow the maximum size of a Java class is to use the octal encoding.
