### ISSUE TITLE
bin/fac nlp --wsj-forward-pos --conll-chain-ner ./target/factorie_2.11-1.2-jar-with-dependencies.jar not found

### ISSUE THREAD

**Issue by napsternxg** [factorie/factorie#363]
When I try to run the example script, I get the following error:
```
$ bin/fac nlp --wsj-forward-pos --conll-chain-ner
./target/factorie_2.11-1.2-jar-with-dependencies.jar not found
```

I appears the `bin/fac` was not updated. I will fix it and send a PR.

**Comment by strubell** [comment]
Oops, thank you!

**Comment by napsternxg** [comment]
@strubell please check my PR and merge.

**Comment by fooSynaptic** [comment]
i followed all the build process still encountered this issue.
