### ISSUE TITLE
Unable to compile with Maven 2?

### ISSUE THREAD

**Issue by mpatek** [factorie/factorie#39]
Hi,

I've tried this with the latest release, and the master branch. I'm getting this error when compiling with maven 2:

```
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error resolving version for 'net.alchim31.maven:scala-maven-plugin':      Plugin requires Maven version 3.0
[INFO] ------------------------------------------------------------------------
[INFO] For more information, run Maven with the -e switch
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8 seconds
[INFO] Finished at: Tue Sep 03 09:48:03 EDT 2013
[INFO] Final Memory: 7M/75M
[INFO] ------------------------------------------------------------------------`
```

Here's my maven version info:

```
Apache Maven 2.2.1 (rdebian-8)
Java version: 1.7.0_25
Java home: /usr/lib/jvm/java-7-openjdk-i386/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux" version: "3.8.0-29-generic" arch: "i386" Family: "unix"
```

I tried with the most recent version of Maven (3.1.0) and was able to compile successfully. So, maybe the requirements should be updated in the documentation?

**Comment by fooSynaptic** [comment]
@alextp 
i encountered network issue while compiling which  get stucked in the Downloading, can you give me some suggestions to accomplish the compile?

`Downloading from info-bliki-repository: http://gwtwiki.googlecode.com/svn/maven-repository/org/json4s/json4s-ast_2.12/3.5.3/json4s-ast_2.12-3.5.3.pom`
